doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Interview:
                type: yml
                dir: '%kernel.project_dir%/config/Doctrine/Interview'
                prefix: 'Interview'
            Money:
                type: yml
                dir: '%kernel.project_dir%/config/Doctrine/Money'
                prefix: 'Money'