version: '3.1'

services:
    app:
        build: .
        depends_on:
            - db
#        volumes:
#            - ./:/app
        env_file:
            -   .env
        ports:
            - 8081:8081
        networks:
            - stack
    db:
        image: mysql:8.0
        restart: on-failure
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=c0B1r0
            - MYSQL_USER=inteview-user
            - MYSQL_PASSWORD=1n73rvi3w
            - MYSQL_DATABASE=inteview
        volumes:
            - interview-db:/var/lib/mysql
        networks:
            - stack
networks:
    stack:

volumes:
    interview-db: