getAllProducts:
    path: /products/
    methods: GET
    controller: App\Controller\ProductController::getAll

createProduct:
    path: /products/
    methods: POST
    controller: App\Controller\ProductController::save


getProduct:
    path: /products/{id}
    methods: GET
    controller: App\Controller\ProductController::getById

updateProduct:
    path: /products/{id}
    methods: PUT
    controller: App\Controller\ProductController::save

deleteProduct:
    path: /products/{id}
    methods: DELETE
    controller: App\Controller\ProductController::remove