# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    defaultPriceCurrency: PLN

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/App/Controller/'
        tags: ['controller.service_arguments']
    App\Command\:
        resource: '../src/App/Command'

    interview.redis.connection:
        class: Redis
        factory: ['Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection']
        arguments: ['%env(resolve:READ_MODEL_URL)%']
    interview.product.projection.adapter:
        class: Symfony\Component\Cache\Adapter\RedisAdapter
        arguments: ['@interview.redis.connection', 'product']

    Interview\Product\Infrastructure\Doctrine\ORM\ServiceEntityRepository:

    Interview\Product\Domain\ProductFactoryInterface:
        class: Interview\Product\Domain\ProductFactory
        arguments:
            $defaultPriceCurrency: '%defaultPriceCurrency%'

    Interview\Product\Domain\ProductRepositoryInterface:
        class: Interview\Product\Infrastructure\Doctrine\ORM\ProductRepository

    Interview\Product\Application\Query\GetProductQueryInterface:
        #class: Interview\Product\Infrastructure\Doctrine\DBAL\Query\GetProductQuery
        alias: Interview\Product\Domain\ProductProjectionInterface

    interview.product.create_product_handler:
        class: Interview\Product\Application\Command\CreateOrUpdateProductHandler
        tags:
            - { name: tactician.handler, command: Interview\Product\Application\Command\CreateProductCommand }

    interview.product.update_product_handler:
        class: Interview\Product\Application\Command\CreateOrUpdateProductHandler
        tags:
            - { name: tactician.handler, command: Interview\Product\Application\Command\UpdateProductCommand }


    interview.product.remove_product_handler:
        class: Interview\Product\Application\Command\RemoveProductHandler
        tags:
            - { name: tactician.handler, typehints: true }

    interview.product.projector:
        class: Interview\Product\Domain\Event\ProductProjector
        tags:
            - { name: kernel.event_listener, event: Interview\Product\Domain\Event\ProductCreatedEvent, method: whenProductCreated }
            - { name: kernel.event_listener, event: Interview\Product\Domain\Event\ProductUpdatedEvent, method: whenProductUpdated }
            - { name: kernel.event_listener, event: Interview\Product\Domain\Event\ProductRemovedEvent, method: whenProductRemoved }

    Interview\Product\Domain\ProductProjectionInterface:
        class: Interview\Product\Infrastructure\Redis\ProductProjection
        arguments: ['@interview.product.projection.adapter']