Interview\Product\Infrastructure\Product:
    type: entity
    repositoryClass: Interview\Product\Infrastructure\ServiceEntityRepository
    table: products
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false
    embedded:
        price:
            class: Money\Money
            columnPrefix: price_
            nullable: false
