Interview\Product\Infrastructure\Product:
    type: entity
    repositoryClass: Interview\Product\Infrastructure\Doctrine\ORM\ServiceEntityRepository
    table: products
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false
        code:
            type: uuid
            nullable: false
            unique: true
    embedded:
        price:
            class: Money\Money
            columnPrefix: price_
            nullable: false