Interview\Product\Domain\Product:
    type: entity
    repositoryClass: Interview\Product\Infrastructure\Doctrine\ORM\ServiceEntityRepository
    table: products
    id:
        id:
            type: uuid
    embedded:
        name:
            class: Interview\Product\Domain\ProductName
            columnPrefix: false
            nullable: false
        price:
            class: Money\Money
            columnPrefix: price_
            nullable: false